name: dart_plugin_template
description: A template for creating dart_eval plugins (Dart only)
version: 0.1.1

environment:
  sdk: ^3.0.0

dependencies:
  dart_eval: ^0.7.9

dev_dependencies:
  lints: ^2.0.0
